n = int(input('Insira um número para criar a tabuada: '))
n1 = int(n*1)
n2 = int(n*2)
n3 = int(n*3)
n4 = int(n*4)
n5 = int(n*5)
n6 = int(n*6)
n7 = int(n*7)
n8 = int(n*8)
n9 = int(n*9)
n10 = int(n*10)

print('|=============|')
print('|___Tabuada___|')
print('|=============|')

print(f'|{n} x 1 = {n1:>4}|')
print(f'|{n} x 2 = {n2:>4}|')
print(f'|{n} x 3 = {n3:>4}|')
print(f'|{n} x 4 = {n4:>4}|')
print(f'|{n} x 5 = {n5:>4}|')
print(f'|{n} x 6 = {n6:>4}|')
print(f'|{n} x 7 = {n7:>4}|')
print(f'|{n} x 8 = {n8:>4}|')
print(f'|{n} x 9 = {n9:>4}|')
print(f'|{n} x 10 = {n10:>3}|')
